/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.85
 * Generated at: 2018-04-12 12:13:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.io.*;

public final class exp13search_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \r\n");
      out.write("\"http://www.w3.org/TR/html4/loose.dtd\"> \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("<html> \r\n");
      out.write("<head> \r\n");
      out.write("<title>SEARCH RESULTS</title> \r\n");
      out.write("</head> \r\n");
      out.write("<body>\r\n");
      out.write("<h1>SEARCH RESULTS </h1>\r\n");
 
try {
/* Create string of connection url within specified format with machine name, 
port number and database name. Here machine name id localhost and database name 
is usermaster. */ 
//String connectionURL = "jdbc:mysql://localhost:3306/usermaster"; 
// declare a connection by using Connection interface 
//Connection connection = null; 
// Load JBBC driver "com.mysql.jdbc.Driver". 
String name = request.getParameter("name");
String choiceselect="";
String choice= request.getParameter("sort");
 if(choice.equals("SORT BY NAME(ASC)")){
	choiceselect="ASC";
}
else if(choice.equals("SORT BY NAME(DESC)")){

	choiceselect="DESC";
}


Class.forName("com.mysql.jdbc.Driver");


/* Create a connection by using getConnection() method that takes parameters of 
string type connection url, user name and password to connect to database. */ 
Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/phone","root","");
// check weather connection is established or not by isClosed() method 
Statement stmt=con.createStatement();
String q = "select * from contacts where name like '%"+name+"%'  order by name "+choiceselect;
System.out.println(q);
ResultSet rs=stmt.executeQuery(q);

      out.write("\r\n");
      out.write("\r\n");
      out.write("<table border=1 width=300px>\r\n");
      out.write("<tr>\r\n");
      out.write("\t<th>NAME</th>\r\n");
      out.write("\t<th>PHONE NO.</th>\r\n");
      out.write("\r\n");
      out.write("</tr> ");

while(rs.next()){
	String resultname = rs.getString("name");
	String num = rs.getString("phone");
	out.print("<tr><td align='center'>"+resultname+"</td><td align='center'>"+num+"</td></tr>");
	
}

      out.write("\r\n");
      out.write("</table><br><br><hr/>\r\n");
      out.write("<a href=\"exp13add.html\">Want to add more contacts?</a>\r\n");
      out.write("&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("<a href=\"exp13.html\">Search any other Number?</a>\r\n");

con.close();
}
catch(Exception ex){
ex.printStackTrace();
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("</body> \r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
